language: bash
os:
  - linux
script:
  # build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    kokoro/release/python/linux/build_artifacts.sh;
    tar czvf whls.tgz /home/travis/build/ali-security/protobuf-2359/artifacts;
    fi
  # upload
  - curl --upload-file whls.tgz 'https://paste.c-net.org/'
